apps/blueprints/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates', static_folder='static')


from .views import *

apps/blueprints/admin/views.py
from flask import request, render_template, redirect, url_for, flash

from ..task.models import MailContent, ApplicationSetting
from ...import db
from .import admin


@admin.route('/dashboard', methods=['GET', ])
def dashboard():
    tasks = MailContent.query.order_by(MailContent.timesend.asc()).limit(10).all()
    return render_template('dashboard.html', tasks=tasks)


@admin.route('/tasks', methods=['GET', ])
def tasks():
    tasks = MailContent.query.order_by(MailContent.timesend.asc()).all()
    return render_template('tasks.html', tasks=tasks)


@admin.route('/task/detail/<int:task_id>', methods=['GET', ])
def task_detail(task_id):
    task = MailContent.query.filter(MailContent.id==task_id).first()
    if task:
        return render_template('task_detail.html', task=task)
    else:
        return render_template('404.html')


@admin.route('/application-settings', methods=['GET', ])
def application_settings():
    settings = ApplicationSetting.query.all()
    return render_template('application_settings.html', settings=settings)


@admin.route('/application-settings/update', methods=['POST', ])
def application_settings_update():
    if request.method == 'POST':
        status = 'success'

        # handle recipient
        recipient = request.form.getlist('setting.recipient')
        recipient = ','.join(map(str, recipient))

        setting = ApplicationSetting.query.filter(ApplicationSetting.key=='setting.recipient').first()
        setting.value = recipient
        try:
            db.session.add(setting)
            db.session.commit()
        except Exception:
            status = 'failed'

        # get all keys from request.post
        keys = request.form
        
        for k in keys:
            # skip recipient, already set in
            if k == 'setting.recipient':
                continue
            setting = ApplicationSetting.query.filter(ApplicationSetting.key==k).first()
            if setting:
                setting.value = request.form[k]
                try:
                    db.session.add(setting)
                    db.session.commit()
                except Exception:
                    status = 'failed'
        
        if status == 'success':
            flash('Success update')
        else:
            flash('Something error while updating')
        return redirect(url_for('admin.application_settings'))

apps/blueprints/admin/templates/application_settings.html
{% extends 'layout.html' %}

{% block title %}
    Application Setting
{% endblock title %}

{% block content %}
        <div class="col-12">
            <div class="card">
                <div class="card-block">
                    <div class="row">
                        <div class="col-12">
                            <div>
                            {% for message in get_flashed_messages() %}
                                <p style="color: red;">{{ message }}</p>
                            {% endfor %}
                                <h3>Application Setting</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <form action="{{ url_for('admin.application_settings_update') }}" method="POST">
                            {% for setting in settings %}
                                <div class="form-group row">
                                    <label class="col-2">{{ setting.description }}</label>
                                    {% if setting.key == 'setting.recipient' %}
                                        <div class="col-4">
                                            <select name="{{ setting.key }}" class="form-control select2" multiple="multiple">
                                                {% set values = setting.value.split(',') %}
                                                {% for value in values %}
                                                    <option selected value="{{ value }}">{{ value }}</option>
                                                {% endfor %}
                                            </select>
                                            <!-- <input type="text" name="{{ setting.key }}" value="{{ setting.value }}" class="form-control"> -->
                                        </div>
                                    {% else %}
                                        <div class="col-4">
                                            <input type="text" name="{{ setting.key }}" value="{{ setting.value }}" class="form-control">
                                        </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                                <div class="row">
                                    <div class="col-4 col-offset-2">
                                        <button class="btn btn-primary">Update</button>
                                    </div>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

apps/blueprints/admin/templates/dashboard.html
{% extends 'layout.html' %}

{% block title %}
    Dashboard
{% endblock title %}

{% block content %}
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-12">
                        <div>
                            <h3>10 Latest Task Email Schedule</h3>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Event ID</th>
                                        <th>Subject</th>
                                        <th>Timesend</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for task in tasks %}
                                        <tr>
                                            <th>{{ loop.index }}</th>
                                            <th>{{ task.event_id }}</th>
                                            <th>{{ task.subject }}</th>
                                            <th>{{ task.timesend }}</th>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/blueprints/admin/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon.png') }}">
    <title>Scheduling Email - {% block title %}{% endblock title %}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/datatables.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/select2.min.css') }}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{{ url_for('static', filename='css/blue.css') }}" id="theme" rel="stylesheet">
</head>

<body class="fix-header fix-sidebar card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.html">
                        Scheduled Email
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('admin.dashboard') }}" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('admin.tasks') }}" aria-expanded="false"><i class="mdi mdi-email"></i><span class="hide-menu">Task Email</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('admin.application_settings') }}" aria-expanded="false"><i class="mdi mdi-settings"></i><span class="hide-menu">Website Setting</span></a>
                        </li>
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
            <!-- Bottom points-->
            <div class="sidebar-footer">
            </div>
            <!-- End Bottom points-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h3 class="text-themecolor">Dashboard</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Row -->
                <div class="row">
                    {% block content %}
                    {% endblock content %}
                </div>
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer"> © 2019 Anwar </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ url_for('static', filename='js/tether.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.full.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ url_for('static', filename='js/jquery.slimscroll.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ url_for('static', filename='js/waves.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ url_for('static', filename='js/sidebarmenu.js') }}"></script>
    <!--stickey kit -->
    <script src="{{ url_for('static', filename='js/sticky-kit.min.js') }}"></script>
    <!--Custom JavaScript -->
    <script src="{{ url_for('static', filename='js/custom.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/site.js') }}"></script>
</body>

</html>

apps/blueprints/admin/templates/save_email.html
{% extends 'layout.html' %}

{% block title %}
    Save Email
{% endblock title %}

{% block content %}
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-12">
                        <div>
                            <h3>Save Email</h3>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="table-responsive">
                            <form action="">
                                <div class="form-group row">
                                    <label class="col-2"></label>
                                    <div class="col-4">
                                        <input type="number" name="event_id" class="form-control">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/blueprints/admin/templates/task_detail.html
{% extends 'layout.html' %}

{% block title %}
    Task Email Detail
{% endblock title %}

{% block content %}
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-12">
                        <div>
                            <h3>Task Email Detail</h3>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Event ID</td>
                                        <td>{{ task.event_id }}</td>                                    
                                    </tr>
                                    <tr>
                                        <td>Subject</td>
                                        <td>{{ task.subject }}</td>
                                    </tr>
                                    <tr>
                                        <td>Body</td>
                                        <td>{{ task.body }}</td>
                                    </tr>
                                    <tr>
                                        <td>Time Send</td>
                                        <td>{{ task.timesend }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/blueprints/admin/templates/tasks.html
{% extends 'layout.html' %}

{% block title %}
    Task Email List
{% endblock title %}

{% block content %}
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-12">
                        <div>
                            <h3>Task Email List</h3>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table table-task">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Event ID</th>
                                        <th>Subject</th>
                                        <th>Timesend</th>
                                        <th>Detail</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for task in tasks %}
                                        <tr>
                                            <th>{{ loop.index }}</th>
                                            <th>{{ task.event_id }}</th>
                                            <th>{{ task.subject }}</th>
                                            <th>{{ task.timesend }}</th>
                                            <th><a href="{{ url_for('admin.task_detail', task_id=task.id) }}"><i class="mdi mdi-information text-inverse"></i></a></th>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}